import React, { useState, useEffect } from 'react';
import axios from '../api/axiosConfig';
import { ENDPOINTS } from '../api/endpoints';
import { useAuth } from '../context/AuthContext';
import jsPDF from 'jspdf';
import './History.css';

const History = () => {
    const { user } = useAuth();
    const [historyList, setHistoryList] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');

    useEffect(() => {
        const fetchHistory = async () => {
            if (!user?.id) return;
            try {
                const [symptomRes, reportRes] = await Promise.all([
                    axios.get(ENDPOINTS.SYMPTOMS_HISTORY(user.id)),
                    axios.get(ENDPOINTS.REPORTS_HISTORY(user.id))
                ]);

                // Normalize and merge history
                const symptoms = (symptomRes.data || []).map(item => ({
                    ...item,
                    display_type: 'symptom',
                    date: item.created_at
                }));
                const reports = (reportRes.data || []).map(item => ({
                    ...item,
                    display_type: 'report',
                    date: item.created_at
                }));

                const merged = [...symptoms, ...reports].sort(
                    (a, b) => new Date(b.date) - new Date(a.date)
                );

                setHistoryList(merged);
            } catch (err) {
                console.error("Failed to fetch history", err);
                setError('Failed to fetch history details.');
            } finally {
                setLoading(false);
            }
        };
        fetchHistory();
    }, [user?.id]);

    const handleDownloadItem = (item) => {
        const doc = new jsPDF();
        const dateStr = new Date(item.date).toLocaleString();

        // Header
        doc.setFontSize(20);
        doc.setTextColor(0, 102, 204);
        doc.text('EarlyCare', 105, 20, { align: 'center' });
        
        doc.setFontSize(14);
        doc.setTextColor(40, 40, 40);
        
        const title = item.display_type === 'symptom' 
            ? 'Symptom Check History Report' 
            : 'Medical Report Analysis History';
            
        doc.text(title, 105, 30, { align: 'center' });
        
        doc.setLineWidth(0.5);
        doc.line(20, 35, 190, 35);

        // Meta Data
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(`Record Date: ${dateStr}`, 20, 45);
        doc.text(`Downloaded: ${new Date().toLocaleString()}`, 20, 52);

        // Details
        let yPos = 65;
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);

        doc.setFont('helvetica', 'bold');
        doc.text('PREDICTED CONDITION:', 20, yPos);
        doc.setFont('helvetica', 'normal');
        yPos += 7;
        doc.text(item.predicted_disease || 'Unknown', 20, yPos);
        yPos += 12;

        doc.setFont('helvetica', 'bold');
        doc.text('RISK LEVEL:', 20, yPos);
        doc.setFont('helvetica', 'normal');
        yPos += 7;
        doc.text(item.risk_level || 'Unknown', 20, yPos);
        yPos += 12;

        if (item.display_type === 'report' && item.file_url) {
            doc.setFont('helvetica', 'bold');
            doc.text('FILE UPLOADED:', 20, yPos);
            doc.setFont('helvetica', 'normal');
            yPos += 7;
            doc.text(item.file_url.split('/').pop(), 20, yPos);
            yPos += 12;
        }

        doc.setFont('helvetica', 'bold');
        doc.text('ANALYSIS SUMMARY:', 20, yPos);
        doc.setFont('helvetica', 'normal');
        yPos += 7;
        
        const analysisText = item.analysis || 'N/A';
        const splitAnalysis = doc.splitTextToSize(analysisText, 170);
        doc.text(splitAnalysis, 20, yPos);
        
        yPos += (splitAnalysis.length * 7) + 10;

        // Disclaimer
        doc.setLineWidth(0.2);
        doc.line(20, yPos, 190, yPos);
        
        doc.setFontSize(9);
        doc.setTextColor(150, 0, 0);
        const disclaimer = "DISCLAIMER: This report is generated by an AI ML model. It is for informational purposes only and NOT a substitute for professional medical advice, diagnosis, or treatment.";
        const splitDisclaimer = doc.splitTextToSize(disclaimer, 170);
        doc.text(splitDisclaimer, 20, yPos + 10);

        doc.save(`EarlyCare_${item.display_type === 'symptom' ? 'Symptom' : 'Report'}_History_${new Date(item.date).toISOString().split('T')[0]}.pdf`);
    };

    if (loading) return <div className="loading">Loading History...</div>;

    return (
        <div className="history-container">
            <h2>Health History</h2>
            {error && <div className="error-message">{error}</div>}

            {historyList.length === 0 ? (
                <p className="no-history">No history found. Try Symptom Check or Upload Reports!</p>
            ) : (
                <div className="history-grid">
                    {historyList.map((item, idx) => (
                        <div key={idx} className={`history-item ${item.display_type}`}>
                            <div className="item-header">
                                <div className="header-info">
                                    <span className="item-type">
                                        {item.display_type === 'symptom' ? '🩺 Symptom Check' : '📄 Report Analysis'}
                                    </span>
                                    <span className="item-date">{new Date(item.date).toLocaleDateString()}</span>
                                </div>
                                <button className="history-download-btn" onClick={() => handleDownloadItem(item)}>
                                    Download
                                </button>
                            </div>
                            <div className="item-body">
                                {item.display_type === 'symptom' ? (
                                    <>
                                        <p><strong>Predicted Condition:</strong> {item.predicted_disease}</p>
                                        <p><strong>Risk Level:</strong> {item.risk_level}</p>
                                        <p><strong>Analysis:</strong> {item.analysis}</p>
                                    </>
                                ) : (
                                    <>
                                        <p><strong>File:</strong> {item.file_url?.split('/').pop() || 'Medical Report'}</p>
                                        <p><strong>Condition:</strong> {item.predicted_disease}</p>
                                        <p><strong>Risk Level:</strong> {item.risk_level}</p>
                                        <p><strong>Analysis:</strong> {item.analysis}</p>
                                    </>
                                )}
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
};

export default History;
